### ISSUE TITLE
Designed Unity Paywall

### ISSUE THREAD

**Issue by odedhb** [app-central/sdk-unity#13]

**Comment by SabreRunner** [comment]
Any more specifications on this? Because I have a basic design already up.
![Screenshot 2021-01-13 130835](https://user-images.githubusercontent.com/10673434/104444514-93ef6480-55a0-11eb-913b-f4526121dcbd.png)
![Screenshot 2021-01-13 130856](https://user-images.githubusercontent.com/10673434/104444538-96ea5500-55a0-11eb-8e34-a3be80b8918d.png)

**Comment by odedhb** [comment]
No, that looks ok for now, we will have a design for superfood soon.
Remember that the design should be configurable.

**Comment by SabreRunner** [comment]
Of course. But it still needs to follow some standard, unless you want developers to build their own.

**Comment by odedhb** [comment]
This is the standard for now:
![](https://user-images.githubusercontent.com/10673434/104444538-96ea5500-55a0-11eb-8e34-a3be80b8918d.png)

Let me know if you need help turning this to a config file.
